version: '3.7'
services:

  api:
    build: .
    image: flask-template:latest
    env_file:
      - .env
    environment:
      - FLASK_ENV=testing
    restart: always
    ports:
      - 8080:8080
    command: "flask run --host=0.0.0.0"
    volumes:
      - .:/app
